-- MySQL Script generated by MySQL Workbench
-- Sat Apr 23 17:07:15 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Group_6_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Group_6_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Group_6_db` DEFAULT CHARACTER SET utf8 ;
USE `Group_6_db` ;

-- -----------------------------------------------------
-- Table `Group_6_db`.`district`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`district` (
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`address` (
  `ID` INT NOT NULL,
  `door` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `add_d` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `add_d_idx` (`add_d` ASC),
  CONSTRAINT `add_d`
    FOREIGN KEY (`add_d`)
    REFERENCES `Group_6_db`.`district` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`user` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `type` DECIMAL(2,0) NOT NULL,
  `user_add` INT NOT NULL,
  PRIMARY KEY (`username`),
  INDEX `user_add_idx` (`user_add` ASC),
  CONSTRAINT `user_add`
    FOREIGN KEY (`user_add`)
    REFERENCES `Group_6_db`.`address` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`customer` (
  `user` VARCHAR(20) NOT NULL,
  `points` INT NULL,
  PRIMARY KEY (`user`),
  CONSTRAINT `username`
    FOREIGN KEY (`user`)
    REFERENCES `Group_6_db`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`owner` (
  `user` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user`),
  CONSTRAINT `ID`
    FOREIGN KEY (`user`)
    REFERENCES `Group_6_db`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`menu` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`restaurant` (
  `rest_ow` VARCHAR(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `work_hour_start` TIME NOT NULL,
  `work_hour_end` TIME NOT NULL,
  `rest_add` INT NOT NULL,
  `rest_menu` INT NOT NULL,
  INDEX `user_idx` (`rest_ow` ASC),
  INDEX `ID_idx` (`rest_add` ASC),
  INDEX `ID_idx1` (`rest_menu` ASC),
  PRIMARY KEY (`rest_ow`, `name`),
  CONSTRAINT `user`
    FOREIGN KEY (`rest_ow`)
    REFERENCES `Group_6_db`.`owner` (`user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rest_add`
    FOREIGN KEY (`rest_add`)
    REFERENCES `Group_6_db`.`address` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rest_menu`
    FOREIGN KEY (`rest_menu`)
    REFERENCES `Group_6_db`.`menu` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`rest_dis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`rest_dis` (
  `district` VARCHAR(45) NOT NULL,
  `rest_ow` VARCHAR(20) NOT NULL,
  `rest_name` VARCHAR(45) NOT NULL,
  INDEX `name_idx` (`rest_name` ASC),
  INDEX `rest_ow_idx` (`rest_ow` ASC),
  CONSTRAINT `name`
    FOREIGN KEY (`district`)
    REFERENCES `Group_6_db`.`district` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rest_name`
    FOREIGN KEY (`rest_name`)
    REFERENCES `Group_6_db`.`restaurant` (`rest_ow`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rest_ow`
    FOREIGN KEY (`rest_ow`)
    REFERENCES `Group_6_db`.`restaurant` (`rest_ow`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`menu_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`menu_item` (
  `ID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(3,2) NOT NULL,
  `type` DECIMAL(2,0) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`review` (
  `ID` INT NOT NULL,
  `rank` DECIMAL(2,2) NOT NULL,
  `comment` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`rest_rev`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`rest_rev` (
  `rest_ow` VARCHAR(20) NOT NULL,
  `rest_name` VARCHAR(45) NOT NULL,
  `review` INT NOT NULL,
  INDEX `name_idx` (`rest_name` ASC),
  INDEX `rest_ow_idx` (`rest_ow` ASC),
  PRIMARY KEY (`review`, `rest_ow`, `rest_name`),
  CONSTRAINT `rest_name_rev`
    FOREIGN KEY (`rest_name`)
    REFERENCES `Group_6_db`.`restaurant` (`rest_ow`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rest_ow_rev`
    FOREIGN KEY (`rest_ow`)
    REFERENCES `Group_6_db`.`restaurant` (`rest_ow`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `review_ID`
    FOREIGN KEY (`review`)
    REFERENCES `Group_6_db`.`review` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`mi_rev`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`mi_rev` (
  `item` INT NOT NULL,
  `review` INT NOT NULL,
  PRIMARY KEY (`review`),
  INDEX `ID_idx` (`item` ASC),
  CONSTRAINT `mi_rev_item`
    FOREIGN KEY (`item`)
    REFERENCES `Group_6_db`.`menu_item` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mi_rev_rev`
    FOREIGN KEY (`review`)
    REFERENCES `Group_6_db`.`review` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`promotion` (
  `ID` INT NOT NULL,
  `cost` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`cart` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`m_mi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`m_mi` (
  `menu` INT NOT NULL,
  `item` INT NOT NULL,
  PRIMARY KEY (`menu`, `item`),
  INDEX `ID_idx` (`item` ASC),
  CONSTRAINT `m_mi_menu`
    FOREIGN KEY (`menu`)
    REFERENCES `Group_6_db`.`menu` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `m_mi_item`
    FOREIGN KEY (`item`)
    REFERENCES `Group_6_db`.`menu_item` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`pro_mi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`pro_mi` (
  `item` INT NOT NULL,
  `promotion` INT NOT NULL,
  PRIMARY KEY (`item`, `promotion`),
  INDEX `ID_idx` (`promotion` ASC),
  CONSTRAINT `pro_mi_pro`
    FOREIGN KEY (`promotion`)
    REFERENCES `Group_6_db`.`promotion` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pro_mi_ID`
    FOREIGN KEY (`item`)
    REFERENCES `Group_6_db`.`menu_item` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`c_mi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`c_mi` (
  `item` INT NOT NULL,
  `cart` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`item`, `cart`),
  INDEX `ID_idx` (`cart` ASC),
  CONSTRAINT `c_mi_c`
    FOREIGN KEY (`cart`)
    REFERENCES `Group_6_db`.`cart` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `c_mi_mi`
    FOREIGN KEY (`item`)
    REFERENCES `Group_6_db`.`menu_item` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`order` (
  `ID` INT NOT NULL,
  `cart` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_idx` (`cart` ASC),
  CONSTRAINT `order_cart`
    FOREIGN KEY (`cart`)
    REFERENCES `Group_6_db`.`cart` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group_6_db`.`c_pro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group_6_db`.`c_pro` (
  `cart` INT NOT NULL,
  `promotion` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`cart`, `promotion`),
  INDEX `ID_idx` (`cart` ASC),
  INDEX `ID_idx1` (`promotion` ASC),
  CONSTRAINT `c_pro_cart`
    FOREIGN KEY (`cart`)
    REFERENCES `Group_6_db`.`cart` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `c_pro_pro`
    FOREIGN KEY (`promotion`)
    REFERENCES `Group_6_db`.`promotion` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
